// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGxuCKxtk4K8LHN8JRL5Ya6CBvkyWWsfE',
    appId: '1:626856174117:web:acb427c2c1eb67d64715cc',
    messagingSenderId: '626856174117',
    projectId: 'flutter-jago-elektronik-1986d',
    authDomain: 'flutter-jago-elektronik-1986d.firebaseapp.com',
    storageBucket: 'flutter-jago-elektronik-1986d.appspot.com',
    measurementId: 'G-4C6XL70MHE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwlbWR0fGHG2yyJ27m064zhB7oAyUR_yg',
    appId: '1:626856174117:android:c1dc5f3171284ecc4715cc',
    messagingSenderId: '626856174117',
    projectId: 'flutter-jago-elektronik-1986d',
    storageBucket: 'flutter-jago-elektronik-1986d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAF6T2u9HRFZZciSRaql3YFX2XrULDicA4',
    appId: '1:626856174117:ios:73b625f7f9f9cf944715cc',
    messagingSenderId: '626856174117',
    projectId: 'flutter-jago-elektronik-1986d',
    storageBucket: 'flutter-jago-elektronik-1986d.appspot.com',
    androidClientId: '626856174117-d1vcto7j0se1u94852adtkkqj710pl1q.apps.googleusercontent.com',
    iosClientId: '626856174117-lhkkart6c9vn6h59co1totoltom751fp.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterJagoElektronik',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAF6T2u9HRFZZciSRaql3YFX2XrULDicA4',
    appId: '1:626856174117:ios:73b625f7f9f9cf944715cc',
    messagingSenderId: '626856174117',
    projectId: 'flutter-jago-elektronik-1986d',
    storageBucket: 'flutter-jago-elektronik-1986d.appspot.com',
    androidClientId: '626856174117-d1vcto7j0se1u94852adtkkqj710pl1q.apps.googleusercontent.com',
    iosClientId: '626856174117-lhkkart6c9vn6h59co1totoltom751fp.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterJagoElektronik',
  );
}
